# Generated by Django 3.1.2 on 2021-02-02 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=40)),
                ('review', models.CharField(max_length=500, null=True)),
                ('rating', models.FloatField(default=2.5)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 2, 3, 0, 31, 13, 801928))),
            ],
        ),
    ]
