# Generated by Django 3.1.2 on 2021-02-15 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210207_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelreview',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 20, 40, 20, 858152)),
        ),
    ]
